// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto.Context;

#nullable disable

namespace Proyecto.Migrations
{
    [DbContext(typeof(TareaContext))]
    [Migration("20220721215801_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Proyecto.Modelos.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("2b91a62d-8567-49ac-b881-a3e3c503d2c0"),
                            Descripcion = "Tareas que estan en espera",
                            Nombre = "Actividades Pendientes",
                            Peso = 5
                        },
                        new
                        {
                            CategoriaId = new Guid("2b91a62d-8567-49ac-b881-a3e3c503d2c1"),
                            Descripcion = "Tareas que se estan realizando en el trascurso del tiempo",
                            Nombre = "Actividades en Curso",
                            Peso = 8
                        },
                        new
                        {
                            CategoriaId = new Guid("2b91a62d-8567-49ac-b881-a3e3c503d2c2"),
                            Descripcion = "Tareas cumplidas o tareas terminadas a tiempo",
                            Nombre = "Actividades Finalizadas",
                            Peso = 22
                        });
                });

            modelBuilder.Entity("Proyecto.Modelos.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("f3bfb392-1eae-4ae4-a27b-83ab9f2777b7"),
                            CategoriaId = new Guid("2b91a62d-8567-49ac-b881-a3e3c503d2c1"),
                            Descripcion = "Se investiga el uso de Entity Framework por Platzi",
                            FechaCreacion = new DateTime(2022, 7, 21, 15, 58, 1, 467, DateTimeKind.Local).AddTicks(6249),
                            FechaFinalizacion = new DateTime(2022, 7, 21, 15, 58, 1, 467, DateTimeKind.Local).AddTicks(6301),
                            Prioridad = 2,
                            Titulo = "Estudiando el curso de Fundamentos Entity Framework"
                        },
                        new
                        {
                            TareaId = new Guid("f3bfb392-1eae-4ae4-a27b-83ab9f2777b8"),
                            CategoriaId = new Guid("2b91a62d-8567-49ac-b881-a3e3c503d2c2"),
                            FechaCreacion = new DateTime(2022, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaFinalizacion = new DateTime(2022, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Prioridad = 2,
                            Titulo = "I Semestre 2022"
                        });
                });

            modelBuilder.Entity("Proyecto.Modelos.Tarea", b =>
                {
                    b.HasOne("Proyecto.Modelos.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Proyecto.Modelos.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
